plugin: aws_ec2
regions:
  - us-east-1               # Replace with your region
host_key: public_ip_address
keyed_groups:
  - prefix: ""
    key: tags.Name
  # Use public IPs for connection
    
filters:
  tag:App: core-banking    # Filter instances by a specific tag
  instance-state-name: running

compose:
  ansible_user: ubuntu
  ansible_host: public_ip_address
# # Add these configurations
# ansible_ssh_user: ubuntu
# compose:
#   ansible_host: public_ip_address

# # Specify your SSH private key
# vars:
#   ansible_ssh_private_key_file: ./terraform/core-banking-key.pem